spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
  threads:
    virtual:
      enabled: true
  application:
    name: finance-manager
transactions-reset-scheduler-cron: "* 0 * * * *"
balance:
  id:
    length: 20
    characters: "0123456789"