spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: ${SHOW_SQL}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
  threads:
    virtual:
      enabled: ${VIRTUAL_THREADS_ENABLED}
transactions-reset-scheduler-cron: ${TRANSACTIONS_RESET_SCHEDULER_CRON}